# Generated by Django 6.0.3 on 2026-03-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='data_ajuizamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_hora_ultima_atualizacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
