# Generated by Django 6.0.3 on 2026-03-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('KEY', models.IntegerField(primary_key=True, serialize=False)),
                ('NUMACORDAO', models.FloatField(blank=True, null=True)),
                ('ANOACORDAO', models.FloatField(blank=True, null=True)),
                ('COLEGIADO', models.TextField(blank=True, null=True)),
                ('AREA', models.TextField(blank=True, null=True)),
                ('TEMA', models.TextField(blank=True, null=True)),
                ('SUBTEMA', models.TextField(blank=True, null=True)),
                ('ENUNCIADO', models.TextField(blank=True, null=True)),
                ('EXCERTO', models.TextField(blank=True, null=True)),
                ('NUMSUMULA', models.FloatField(blank=True, null=True)),
                ('DATASESSAOFORMATADA', models.TextField(blank=True, null=True)),
                ('AUTORTESE', models.TextField(blank=True, null=True)),
                ('FUNCAOAUTORTESE', models.TextField(blank=True, null=True)),
                ('TIPOPROCESSO', models.TextField(blank=True, null=True)),
                ('TIPORECURSO', models.TextField(blank=True, null=True)),
                ('INDEXACAO', models.TextField(blank=True, null=True)),
                ('INDEXADORESCONSOLIDADOS', models.TextField(blank=True, null=True)),
                ('PARAGRAFOLC', models.TextField(blank=True, null=True)),
                ('REFERENCIALEGAL', models.TextField(blank=True, null=True)),
                ('PUBLICACAOAPRESENTACAO', models.TextField(blank=True, null=True)),
                ('PARADIGMATICO', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'docs',
                'managed': False,
            },
        ),
    ]
